### ISSUE TITLE
Resolving a taxonomy with refresh=true fails with exception

### ISSUE THREAD

**Issue by Pfeil** [FC4E-T4-3/type-api#67]
It does not happen for types as it seems, but at least for taxonomies (I didn't test the rest yet). I used the swagger UI to execute the following command:

```bash
# curl equivalent given by swagger UI
curl -X 'GET' \
  'http://localhost:8080/v1/taxonomy/21.T11969/ffbaf58f1231628f9ac2?refresh=true' \
  -H 'accept: application/xml'
```

With `refresh=false` it works, but with true, it returns `Error: response status is 500` in the swagger UI. There is an exception within the container (click on the short version to expand):

<details>

<summary>

```plain
typeapi-1    | 12:29:28.292 [http-nio-8080-exec-2] INFO  c.f.d.Controllers.TaxonomyController - Retrieving taxonomy node 
typeapi-1    | 12:29:28.302 [http-nio-8080-exec-2] INFO  com.fce4.dtrtoolkit.TypeService - Adding Type 21.T11969/ffbaf58f1231628f9ac2 to the cache
typeapi-1    | 12:29:28.943 [http-nio-8080-exec-2] INFO  com.fce4.dtrtoolkit.TypeService - Adding Type 21.T11969/ffbaf58f1231628f9ac2 to the cache was successful
typeapi-1    | 12:29:28.946 [http-nio-8080-exec-2] INFO  com.fce4.dtrtoolkit.TypeService - Retrieving pid 21.T11969/ffbaf58f1231628f9ac2 via handle and caching...
typeapi-1    | 12:29:28.947 [http-nio-8080-exec-2] INFO  com.fce4.dtrtoolkit.TypeService - Adding Type 21.T11969/ffbaf58f1231628f9ac2 to the cache
typeapi-1    | 12:29:30.087 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.typesense.api.exceptions.RequestMalformed:
typeapi-1    | Request failed with status code: 400.Server said: Field `unit` has been declared in the schema, but is not found in the document.] with root cause
typeapi-1    | org.typesense.api.exceptions.RequestMalformed: null
```

</summary>

```plain
typeapi-1    | 12:29:28.292 [http-nio-8080-exec-2] INFO  c.f.d.Controllers.TaxonomyController - Retrieving taxonomy node 
typeapi-1    | 12:29:28.302 [http-nio-8080-exec-2] INFO  com.fce4.dtrtoolkit.TypeService - Adding Type 21.T11969/ffbaf58f1231628f9ac2 to the cache
typeapi-1    | 12:29:28.943 [http-nio-8080-exec-2] INFO  com.fce4.dtrtoolkit.TypeService - Adding Type 21.T11969/ffbaf58f1231628f9ac2 to the cache was successful
typeapi-1    | 12:29:28.946 [http-nio-8080-exec-2] INFO  com.fce4.dtrtoolkit.TypeService - Retrieving pid 21.T11969/ffbaf58f1231628f9ac2 via handle and caching...
typeapi-1    | 12:29:28.947 [http-nio-8080-exec-2] INFO  com.fce4.dtrtoolkit.TypeService - Adding Type 21.T11969/ffbaf58f1231628f9ac2 to the cache
typeapi-1    | 12:29:30.087 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.typesense.api.exceptions.RequestMalformed:
typeapi-1    | Request failed with status code: 400.Server said: Field `unit` has been declared in the schema, but is not found in the document.] with root cause
typeapi-1    | org.typesense.api.exceptions.RequestMalformed: null
typeapi-1    | 	at org.typesense.api.ApiCall.getException(ApiCall.java:97)
typeapi-1    | 	at org.typesense.api.ApiCall.makeRequest(ApiCall.java:179)
typeapi-1    | 	at org.typesense.api.ApiCall.post(ApiCall.java:136)
typeapi-1    | 	at org.typesense.api.Documents.upsert(Documents.java:41)
typeapi-1    | 	at com.fce4.dtrtoolkit.TypeSearch.upsertEntry(TypeSearch.java:169)
typeapi-1    | 	at com.fce4.dtrtoolkit.TypeService.addType(TypeService.java:220)
typeapi-1    | 	at com.fce4.dtrtoolkit.TypeService.addAllChildren(TypeService.java:345)
typeapi-1    | 	at com.fce4.dtrtoolkit.TypeService.checkAdd(TypeService.java:319)
typeapi-1    | 	at com.fce4.dtrtoolkit.TypeService.getValidation(TypeService.java:285)
typeapi-1    | 	at com.fce4.dtrtoolkit.TypeService.cacheSchema(TypeService.java:163)
typeapi-1    | 	at com.fce4.dtrtoolkit.TypeService.checkAdd(TypeService.java:327)
typeapi-1    | 	at com.fce4.dtrtoolkit.TypeService.getTaxonomyNode(TypeService.java:256)
typeapi-1    | 	at com.fce4.dtrtoolkit.Controllers.TaxonomyController.getTaxonomyNode(TaxonomyController.java:91)
typeapi-1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
typeapi-1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
typeapi-1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
typeapi-1    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
typeapi-1    | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
typeapi-1    | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
typeapi-1    | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
typeapi-1    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
typeapi-1    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
typeapi-1    | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
typeapi-1    | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
typeapi-1    | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
typeapi-1    | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
typeapi-1    | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
typeapi-1    | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705)
typeapi-1    | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
typeapi-1    | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
typeapi-1    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
typeapi-1    | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
typeapi-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
typeapi-1    | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
typeapi-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
typeapi-1    | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
typeapi-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
typeapi-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
typeapi-1    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
typeapi-1    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
typeapi-1    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
typeapi-1    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
typeapi-1    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
typeapi-1    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
typeapi-1    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
typeapi-1    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
typeapi-1    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
typeapi-1    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
typeapi-1    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
typeapi-1    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
typeapi-1    | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
typeapi-1    | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
typeapi-1    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
typeapi-1    | 	at java.base/java.lang.Thread.run(Thread.java:840)
```

</details

**Comment by Lienhop** [comment]
Issue fixed, this was a problem for all types except ones describing schema elements.
